services:
  Evrinoma\ContractBundle\Controller\HierarchyApiController:
    alias: evrinoma.contract.hierarchy.api.controller
    public: true

  evrinoma.contract.hierarchy.api.controller:
    class: Evrinoma\ContractBundle\Controller\HierarchyApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.contract.hierarchy.command.manager'
      - '@evrinoma.contract.hierarchy.query.manager'
    autowire: true

  evrinoma.contract.hierarchy.factory:
    class: Evrinoma\ContractBundle\Factory\HierarchyFactory
    public: true
    arguments:

  evrinoma.contract.hierarchy.repository:
    class: Evrinoma\ContractBundle\Repository\Hierarchy\HierarchyRepository
    public: true
    arguments:

  evrinoma.contract.hierarchy.command.manager:
    class: Evrinoma\ContractBundle\Manager\Hierarchy\CommandManager
    arguments:
      - '@evrinoma.contract.hierarchy.validator'
      - '@evrinoma.contract.hierarchy.repository'
      - '@evrinoma.contract.hierarchy.factory'

  evrinoma.contract.hierarchy.query.manager:
    class: Evrinoma\ContractBundle\Manager\Hierarchy\QueryManager
    arguments:
      - '@evrinoma.contract.hierarchy.repository'

  evrinoma.contract.hierarchy.validator:
    class: Evrinoma\ContractBundle\Validator\HierarchyValidator
    public: true
    arguments:

  Evrinoma\ContractBundle\Validator\HierarchyValidator:
    alias: evrinoma.contract.hierarchy.validator

#  evrinoma.contract.form.rest.hierarchy:
#    class: Evrinoma\ContractBundle\Form\Rest\HierarchyChoiceType
#    arguments:
#      - '@evrinoma.contract.hierarchy.query.manager'
#    tags: { - name: form.type }
#
#  Evrinoma\ContractBundle\Form\Rest\HierarchyChoiceType:
#    alias: evrinoma.contract.form.rest.hierarchy
#    public: true