services:

  evrinoma.contract.fixtures.type:
    class: Evrinoma\ContractBundle\Fixtures\TypeFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.contract.fixtures.hierarchy:
    class: Evrinoma\ContractBundle\Fixtures\HierarchyFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.contract.fixtures.contract:
    class: Evrinoma\ContractBundle\Fixtures\ContractFixtures
    tags:
      - { name: doctrine.fixture.orm }

  evrinoma.contract.fixtures.side:
    class: Evrinoma\ContractBundle\Fixtures\SideFixtures
    tags:
      - { name: doctrine.fixture.orm }


