services:
  evrinoma.contract.constraint.property.contract.type:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Type

  evrinoma.contract.constraint.property.contract.hierarchy:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Hierarchy

  evrinoma.contract.constraint.property.contract.description:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Description

  evrinoma.contract.constraint.property.contract.name:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Name

  evrinoma.contract.constraint.property.contract.number:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Number
