services:
  evrinoma.contract.constraint.contract.property.type:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Type

  evrinoma.contract.constraint.contract.property.hierarchy:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Hierarchy

  evrinoma.contract.constraint.contract.property.description:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Description

  evrinoma.contract.constraint.contract.property.name:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Name

  evrinoma.contract.constraint.contract.property.number:
    class: Evrinoma\ContractBundle\Constraint\Property\Contract\Number
