services:
  evrinoma.contract.constraint.side.left:
    class: Evrinoma\ContractBundle\Constraint\Side\Left

  evrinoma.contract.constraint.side.right:
    class: Evrinoma\ContractBundle\Constraint\Side\Right
