services:
  evrinoma.contract.constraint.side.property.left:
    class: Evrinoma\ContractBundle\Constraint\Property\Side\Left

  evrinoma.contract.constraint.side.property.right:
    class: Evrinoma\ContractBundle\Constraint\Property\Side\Right
